#Very basic make file for building the project and cleaning the executables when necesary
# Any file to add to which is already defining a lot of make file settings, then we need to use "include" e.g. include C:/myFolder/include/MakeDefs.win64
CFLAGS=-Wall -g
clean:
	rm -f BasicFile
all:
	CFLAGS=-Wall -g
	-MyFile.o -MyFile1.o